routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------------------------------ AUTH ROUTE SECTION -------------------------------------------------*/
    Route::get('/logout', 'Auth\LoginController@logout');
    
    Auth::routes();

Route::group(['middleware' => 'ip'], function() {

    Route::get('/', function () {
        
        return redirect('/home');
    });

    

    /*-------------------------------------------END OF ROUTE SECTION---------------------------------------------------*/
    Route::group(['middleware'=>'auth'],function(){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/load-more','HomeController@load_more');

    Route::get('/notifications', 'NotificationController@index');
    Route::delete('profile/{user}/notifications', function(App\User $user) {
        $user->notifications->map(function($n) {
            $n->markAsRead();
        });

        return back();
    });


    /*----------------------------------------------Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        
        Route::get('/leads/bucket-lists','LeadController@bucket_list');
        Route::get('/leads/bucket-lists-data','LeadController@bucket_list_data');
        Route::get('/leads/export','LeadController@export');
        Route::post('/leads/upload','LeadController@upload');
        Route::get('/leads/import','LeadController@import');
        Route::post('/leads/import/store','LeadController@storeimport');
        Route::get('/leads/{lead}/profile','LeadController@profile');
        Route::post('/leads/{lead}/update','LeadController@realtimeUpdate');
        Route::post('/leads/store/notes','LeadController@storenotes');
        Route::post('/leads/delete/notes','LeadController@deletenotes');
        Route::get('/leads/{note}/download','LeadController@download_notes_file');
        Route::post('/leads/notes/{note}/update','LeadController@update_note');
        Route::post('/leads/filter','LeadController@filter');
        Route::post('/leads/assign','LeadController@assign_leads');
        Route::get('leads/getdata','LeadController@getData');
        Route::post('/leads/getbranchdata','LeadController@getbranchdata');
        Route::get('leads/getfilterdata/{data}','LeadController@getFilterData');
        
    
    });
    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        Route::resource('/leads','LeadController');
    });
    /*------------------------------------------End of Leads-------------------------------------------------*/




    /*----------------------------------------------Entrust Routes------------------------------------------------------*/
    Route::group(['prefix'=>''],function(){
        Route::resource('/ipaddress','IpAddressCheckerController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/permission','PermissionController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/role','RoleController');
    });

    /*------------------------------------------End of Entrust Routes-------------------------------------------------*/

    
    /*----------------------------------------------User Routes-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/user','UserController');
    
    });

    /*------------------------------------------End of User Routes-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/company','CompanyController');
    });

    /*------------------------------------------End of Company-------------------------------------------------*/


    /*----------------------------------------------File -----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('files/proposals','FileController@proposals');
        Route::get('files/other-files','FileController@other_files');
        Route::post('files/download','FileController@download');
        Route::resource('/files','FileController');
    });

    /*------------------------------------------End of file-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/branch','BranchController');
        Route::post('/branch/getdata','BranchController@getdata');
    });

    /*--
    
    /*----------------------------------------------User Profile-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/profile','ProfileController');
    });

    /*------------------------------------------End of User Profile-------------------------------------------------*/

    /*----------------------------------------------Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/limit','LimitLeadsController');
    
    });


    /*----------------------------------------------End of Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('/migration/import','MigrationController@import');
        Route::post('/migration/upload','MigrationController@upload');
        Route::post('/migration/import/store','MigrationController@storefile');
        Route::get('/migration','MigrationController@import');  
    });

    /*------------------------------------------End of Leads-------------------------------------------------*/

    /*------------------------------------------Quota Routes-----------------------------------------------------------*/
        
        Route::resource('/quota','QuotaController');
    /*------------------------------------------End of Leads-------------------------------------------------*/

    }); //End of Middleware group

});

resources/views/modules/account/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
     @if(isset($userdata))
     <form role="form" action="{{ url('user/'.$userdata->id) }}" id="user-form" method="POST" enctype="multipart/form-data">
     <input type="hidden" name="_method" value="PUT">
     @else
        <form role="form" action="{{ route('user.store') }}" id="user-form" method="POST">
     @endif   
        @csrf
         <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Create new User </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">  
                        <div class="row">
                            <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">User Info</h3>
                                    <p style="color:#1ab394;">*User can change their info dynamically on their profile settings.</p>
                                    <div class="form-group"><label>Firstname</label> <input type="text" name="firstname" value="@if(isset($userdata)){{ ucfirst($userdata->firstname) }}@endif" placeholder="Enter Firstname" class="form-control" required> </div>
                                    <div class="form-group"><label>Lastname</label> <input type="text" name="lastname" value="@if(isset($userdata)){{ ucfirst($userdata->lastname) }}@endif" placeholder="Enter Lastname" class="form-control" required></div>
                                    <div class="form-group"><label>Primary Email</label> <input type="email" name="email" value="@if(isset($userdata)){{ $userdata->email }}@endif" placeholder="Enter Primary Email" class="form-control" required></div>
                                    <div class="form-group"><label>Profile Picture</label> <input type="file" name="profile"   class="form-control" ></div>
                                   
                                   
                                        <h4>Account Status</h4>
                                        <select name="status" id="status" class="form-control" required @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif>                                     
                                            @foreach ($status as $s)
                                                <option value="{{ $s->id }}" @if(isset($userdata) && $userdata->status == $s->id) selected="selected" @endif>
                                                        {{ $s->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                    
                            </div>

                            <div class="col-sm-6">
                                  
                                    <h4>Company Info</h4>
                                    <p style="color:#1ab394;">*Company info can be change if employee is transfered to another company.</p>
                                    <div class="form-group">
                                        <label>Company Name</label>
                                        <select name="company" id="company" class="form-control" required @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif>
                                        <option value="0">Select Company</option>
                                            @foreach ($company as $c)
                                                <option value="{{ $c->id }}" @if(isset($userdata) && $userdata->company_id == $c->id) selected="selected" @endif>
                                                        {{ $c->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group" id="branch_ajax">
                                       
                                        @if(isset($userdata->branch_id))
                                         <label>Branch Name</label>                                       
                                        <select name="branch" id="branch" class="form-control" required @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif>
                                                @foreach ($userdata->company->branches as $b)
                                                    <option value="{{ $b->id }}" @if(isset($userdata) && $userdata->branch_id == $b->id) selected="selected" @endif>
                                                            {{ $b->name }}
                                                    </option>
                                                @endforeach
                                        </select>
                                        @endif

                                    </div>
                                    
                                        <h4>User Credentials</h4>
                                        <p style="color:#1ab394;">*Updating credentials require to input your current password.</p>
                                        <div class="form-group"><label>Username</label> <input type="text" name="username" value="@if(isset($userdata)){{ $userdata->username }}@endif" placeholder="Enter Username" class="form-control" @if(isset($userdata))disabled @else required @endif></div>
                                        @if(isset($userdata))
                                            <div class="form-group"><label>Current Password</label> <input type="password" name="current-password" placeholder="Enter Current Password" class="form-control" @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif></div>
                                        @endif

                                        <div class="form-group"><label>@if(isset($userdata)) New @endif Password</label> <input type="password" name="password" placeholder="Enter @if(isset($userdata)) New @endif Password" class="form-control" required @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif></div>
                                        <div class="form-group"><label>Confirm @if(isset($userdata)) New @endif Password</label> <input type="password" name="confirm-password" placeholder="Confirm @if(isset($userdata)) New @endif Password" class="form-control" required @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif></div>
                                  
                                        <div>
                                        <button  class="ladda-button btn btn-primary pull-right" data-style="slide-right" @if(auth()->user()->hasRole(['administrator','superadmin','lead.researcher'])) id="submit-user"  type="button" @else type="submit]"  @endif >@if(isset($userdata)) Update @else Create @endif</button>
                                        </div>
                                      
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            @if(auth()->user()->hasRole(['superadmin','administrator','lead.researcher']))
            <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title"> 
                                <h5>Assign User Role</h5>
                                <div class="ibox-tools">
                                    <a class="collapse-link">
                                        <i class="fa fa-chevron-up"></i>
                                    </a>

                                    <a class="close-link">
                                        <i class="fa fa-times"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="ibox-content">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover dataTables-user-role" >
                                    <thead>
                                        <tr>
                                            <th style="width:5%;"><div class="i-checks"><label> <input type="checkbox" value="" id="check-all-roles"></label></div></th>
                                            <th>Name</th>
                                            <th>Description</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($roles as $role)
                                        <tr>
                                            <td>

                                            @if(isset($userdata))
                                                @php
                                                    $checked = '';
                                            @endphp   

                                                @foreach($userdata->getRoles as $userrole)
                                                    @if($role->id ==  $userrole->role_id)
                                                        @php
                                                                $checked = 'checked';
                                                        @endphp   
                                                    @endif
                                                @endforeach
                                            @endif    
                                            
                                                <div class="i-checks"><label> <input type="checkbox" value="{{ $role->id }}" name="roles[]" id="roles" @if(isset($userdata)){{ $checked }} @endif @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif></label></div></td>
                                            
                                            <td style="color:#1ab394;">{{ $role->display_name }}</td>
                                            <td>{{ $role->description }}</td>
                                        </tr>
                            @endforeach
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th style="width:5%;"><div class="i-checks"><label> <input type="checkbox" value="" id="check-all-roles" @if(!auth()->user()->hasRole(['superadmin','administrator']))  disabled="disabled"  @endif></label></div></th>
                                            <th>Name</th>
                                            <th>Description</th>
                                        </tr>
                                    </tfoot>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            @endif
       </form>
    </div>
@endsection

@section('custom_js')
<script>
        $(document).ready(function(){
            $("#check-all-roles").on("ifUnchecked",function(event){
                 //uncheck all checkboxes
                 $("input[type='checkbox']").iCheck("uncheck");
            });

            $("#check-all-roles").on("ifChecked",function(event){
                 //uncheck all checkboxes
                 $("input[type='checkbox']").iCheck("check");
            });
            
            $("#submit-user").on("click",function(e){
                var roles = $('input[type=checkbox]');


                if(roles.filter(":checked").length == 0){
                    swal({
                        title: "Missing Inputs",
                        text: "Please assign role to user.",
                        confirmButtonColor: "#1ab394"
                    });
                }else{
                    $("#user-form").submit();
                }
            });
            

            $("#company").on("change",function(){
                    var id  = $("#company").val();
                    var url = "/branch/getdata";
                     
                    $.ajax({
                            type:"POST",
                            url:url,                              
                            data:{
                            id:id,
                            _token: "{{ csrf_token() }}",       
                            },
                            success:function(result){
                               $("#branch_ajax").html(result);
                            },
                            error:function(error){
                                console.log(error);         
                            }
                            
                    });
            });
        });
    </script>
@endsection

resources/views/modules/account/lists.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
         <div class="row">
            
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>User Lists</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                                <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-permission" >
                            <thead>
                                <tr>
                                    <th style="width:5%;"></th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Status</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                             @foreach($users as $user)
                                <tr>
                                    <td><img src="{{ asset('storage/files/users/'.$user->avatar) }}" alt="" class="img-circle" width="30px" height="30px"></td>
                                    <td style="color:#1ab394;"><a href="{{ url('user/'.$user->id.'/edit') }}">{{ $user->fullname() }}</a></td>            
                                    <td>{{ $user->username }}  </td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        @foreach($user->getRoles as $role)
                                            <label class="{{ $role->getRole->class }}">{{ $role->getRole->display_name }}</label>
                                        @endforeach
                                    </td>
                                    <td>
                                        <label class="label @if($user->status == 1) label-primary @else label-danger @endif">{{ $user->getstatus['name']}}</label>
                                    </td>
                                </tr>
                             @endforeach 
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th style="width:5%;"></th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Status</th>
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
           
       </div>
    </div>
@endsection

@section('custom_js')

@endsection

resources/views/modules/account/profile.blade.php
@extends('layouts.master')

@section('content')
<div class="wrapper wrapper-content">
    <div class="row animated fadeInRight">
        <div class="col-md-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Profile Detail</h5>
                </div>
                <div>
                    <div class="ibox-content no-padding border-left-right">
                        <img alt="image" class="img-responsive" src="{{ asset('storage/files/users/'.auth()->user()->avatar) }}">
                    </div>
                    <div class="ibox-content profile-content">
                        <h4><strong>{{ $user->fullname() }}</strong></h4>
                        <p> <i class="fa fa-drupal"></i>
                        @foreach($user->getRoles as $role)
                        <label class="{{ $role->getRole->class }}">{{ $role->getRole->display_name }}</label>
                         @endforeach
                        </p>
                        <h5>
                            About me
                        </h5>
                        <p>
                        "One of the best programming skills you can have is knowing when to walk away for awhile." 
                        </p>
                        <p class="pull-right"> - Oscar Godson</p>
                        <div class="row m-t-lg">
                            <div class="col-md-4">
                                <span class="bar">5,3,9,6,5,9,7,3,5,2</span>
                                <h5><strong>169</strong> <br> Sold Author</h5>
                            </div>
                            <div class="col-md-4">
                                <span class="line">5,3,9,6,5,9,7,3,5,2</span>
                                <h5><strong>28</strong> <br>Total Author's</h5>
                            </div>
                            <div class="col-md-4">
                                <span class="bar">5,3,2,-1,-3,-2,2,3,5,2</span>
                                <h5><strong>240</strong> <br>Rank</h5>
                            </div>
                        </div>
                        <div class="user-button">
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="button" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i> Send Mail</button>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Activites</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Config option 1</a>
                            </li>
                            <li><a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <div>
                        <div class="feed-activity-list">

                            <div class="feed-element">
                                <a href="#" class="pull-left">
                                    <img alt="image" class="img-circle" src="{{ asset('storage/files/users/'.auth()->user()->avatar) }}">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right text-navy">1m ago</small>
                                    <strong>Sandra Momot</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Today 4:21 pm - 12.06.2014</small>
                                    <div class="actions">
                                        <a class="btn btn-xs btn-white"><i class="fa fa-thumbs-up"></i> Like </a>
                                        <a class="btn btn-xs btn-danger"><i class="fa fa-heart"></i> Love</a>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <button class="btn btn-primary btn-block m"><i class="fa fa-arrow-down"></i> Show More</button>

                    </div>

                </div>
            </div>

        </div>
</div>
@endsection