routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------------------------------ AUTH ROUTE SECTION -------------------------------------------------*/
    Route::get('/logout', 'Auth\LoginController@logout');
    
    Auth::routes();

Route::group(['middleware' => 'ip'], function() {

    Route::get('/', function () {
        
        return redirect('/home');
    });

    

    /*-------------------------------------------END OF ROUTE SECTION---------------------------------------------------*/
    Route::group(['middleware'=>'auth'],function(){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/load-more','HomeController@load_more');

    Route::get('/notifications', 'NotificationController@index');
    Route::delete('profile/{user}/notifications', function(App\User $user) {
        $user->notifications->map(function($n) {
            $n->markAsRead();
        });

        return back();
    });


    /*----------------------------------------------Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        
        Route::get('/leads/bucket-lists','LeadController@bucket_list');
        Route::get('/leads/bucket-lists-data','LeadController@bucket_list_data');
        Route::get('/leads/export','LeadController@export');
        Route::post('/leads/upload','LeadController@upload');
        Route::get('/leads/import','LeadController@import');
        Route::post('/leads/import/store','LeadController@storeimport');
        Route::get('/leads/{lead}/profile','LeadController@profile');
        Route::post('/leads/{lead}/update','LeadController@realtimeUpdate');
        Route::post('/leads/store/notes','LeadController@storenotes');
        Route::post('/leads/delete/notes','LeadController@deletenotes');
        Route::get('/leads/{note}/download','LeadController@download_notes_file');
        Route::post('/leads/notes/{note}/update','LeadController@update_note');
        Route::post('/leads/filter','LeadController@filter');
        Route::post('/leads/assign','LeadController@assign_leads');
        Route::get('leads/getdata','LeadController@getData');
        Route::post('/leads/getbranchdata','LeadController@getbranchdata');
        Route::get('leads/getfilterdata/{data}','LeadController@getFilterData');
        
    
    });
    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        Route::resource('/leads','LeadController');
    });
    /*------------------------------------------End of Leads-------------------------------------------------*/




    /*----------------------------------------------Entrust Routes------------------------------------------------------*/
    Route::group(['prefix'=>''],function(){
        Route::resource('/ipaddress','IpAddressCheckerController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/permission','PermissionController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/role','RoleController');
    });

    /*------------------------------------------End of Entrust Routes-------------------------------------------------*/

    
    /*----------------------------------------------User Routes-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/user','UserController');
    
    });

    /*------------------------------------------End of User Routes-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/company','CompanyController');
    });

    /*------------------------------------------End of Company-------------------------------------------------*/


    /*----------------------------------------------File -----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('files/proposals','FileController@proposals');
        Route::get('files/other-files','FileController@other_files');
        Route::post('files/download','FileController@download');
        Route::resource('/files','FileController');
    });

    /*------------------------------------------End of file-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/branch','BranchController');
        Route::post('/branch/getdata','BranchController@getdata');
    });

    /*--
    
    /*----------------------------------------------User Profile-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/profile','ProfileController');
    });

    /*------------------------------------------End of User Profile-------------------------------------------------*/

    /*----------------------------------------------Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/limit','LimitLeadsController');
    
    });


    /*----------------------------------------------End of Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('/migration/import','MigrationController@import');
        Route::post('/migration/upload','MigrationController@upload');
        Route::post('/migration/import/store','MigrationController@storefile');
        Route::get('/migration','MigrationController@import');  
    });

    /*------------------------------------------End of Leads-------------------------------------------------*/

    /*------------------------------------------Quota Routes-----------------------------------------------------------*/
        
        Route::resource('/quota','QuotaController');
    /*------------------------------------------End of Leads-------------------------------------------------*/

    }); //End of Middleware group

});

resources/views/modules/ipaddress/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
           <div class="col-lg-5">
               <div class="ibox float-e-margins">
                   <div class="ibox-title">
                       <h5>Enter Ip Address </h5>
                       <div class="ibox-tools">
                           <a class="collapse-link">
                               <i class="fa fa-chevron-up"></i>
                           </a>
                           <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                               <i class="fa fa-wrench"></i>
                           </a>
                          
                           <a class="close-link">
                               <i class="fa fa-times"></i>
                           </a>
                       </div>
                   </div>
                   <div class="ibox-content">
                       <div class="row">
                           <div class="col-sm-12">                                   
                                @if(isset($ipaddressdata))
                                    <form role="form" action="{{ url('ipaddress/'.$ipaddressdata->id) }}" method="POST">
                                    <input type="hidden" name="_method" value="PUT">
                                    @else
                                    <form role="form" action="{{ route('ipaddress.store') }}" method="POST">   
                                    @endif                            
                                    @csrf
                                    <div class="form-group"><label>IP Name</label> <input type="text" name="name" value="@if(isset($ipaddressdata)) {{ $ipaddressdata->name }} @endif" placeholder="Enter Ip Name" class="form-control" required></div>
                                    <div class="form-group"><label>IP Address</label> <input type="text" value="@if(isset($ipaddressdata)) {{ $ipaddressdata->value }} @endif" name="value" placeholder="Enter Ip Address" class="form-control" required> </div>
                                    
                                    <button class="ladda-button btn btn-primary pull-right" data-style="slide-right">@if(isset($ipaddressdata)) Update @else Save @endif</button>                               
                                  </form>          
                            </div>                                 
                      </div>
                           
                   </div>
               </div>
           </div>
           <div class="col-lg-7">
               <div class="ibox float-e-margins">
                   <div class="ibox-title">
                       <h5>Ip Address Lists</h5>
                       <div class="ibox-tools">
                           <a class="collapse-link">
                               <i class="fa fa-chevron-up"></i>
                           </a>
                           <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                               <i class="fa fa-wrench"></i>
                           </a>
                               <ul class="dropdown-menu dropdown-user">
                               <li><a href="#">Config option 1</a>
                               </li>
                               <li><a href="#">Config option 2</a>
                               </li>
                           </ul>
                           <a class="close-link">
                               <i class="fa fa-times"></i>
                           </a>
                       </div>
                   </div>
                   <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-permission" >
                                <thead>
                                    <tr>
                                        <th>IP Name</th>
                                        <th>IP Address</th>                                    
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($ipaddresses as $ipaddress)
                                    <tr>
                                        <td ><a href="{{ url('ipaddress/'.$ipaddress->id.'/edit') }}" style="color:#1ab394;">{{ $ipaddress->name }}</a></td>
                                        <td>{{ $ipaddress->value}}</td>
                                    </tr>
                                    @endforeach   
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>IP Name</th>
                                        <th>IP Address</th>                                        
                                    </tr>
                                </tfoot>
                            </table>
                       </div>
                   </div>
               </div>                
           </div>
        </div>
      </div>
  



@endsection

resources/views/modules/ipaddress/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
         <div class="row">
            
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Ip Address Lists</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                                <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-permission" >
                            <thead>
                                <tr>
                                    <th>Ip Name</th>
                                    <th>Ip Address</th>
                                  
                                
                                </tr>
                            </thead>
                            <tbody>
                             @foreach($ipaddresses as $ipaddress)
                                <tr>
                                    <td style="color:#1ab394;"><a href="{{ url('ipaddress/'.$ipaddress->id.'/edit/')}}">{{ $ipaddress->name }}</a></td>
                                    <td>{{ $ipaddress->value }}</td>
                                  
                                </tr>
                             @endforeach   
                             
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Ip Name</th>
                                    <th>Ip Address</th>
                                    
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
           
       </div>
    </div>
@endsection

@section('custom_js')

@endsection