routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------------------------------ AUTH ROUTE SECTION -------------------------------------------------*/
    Route::get('/logout', 'Auth\LoginController@logout');
    
    Auth::routes();

Route::group(['middleware' => 'ip'], function() {

    Route::get('/', function () {
        
        return redirect('/home');
    });

    

    /*-------------------------------------------END OF ROUTE SECTION---------------------------------------------------*/
    Route::group(['middleware'=>'auth'],function(){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/load-more','HomeController@load_more');

    Route::get('/notifications', 'NotificationController@index');
    Route::delete('profile/{user}/notifications', function(App\User $user) {
        $user->notifications->map(function($n) {
            $n->markAsRead();
        });

        return back();
    });


    /*----------------------------------------------Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        
        Route::get('/leads/bucket-lists','LeadController@bucket_list');
        Route::get('/leads/bucket-lists-data','LeadController@bucket_list_data');
        Route::get('/leads/export','LeadController@export');
        Route::post('/leads/upload','LeadController@upload');
        Route::get('/leads/import','LeadController@import');
        Route::post('/leads/import/store','LeadController@storeimport');
        Route::get('/leads/{lead}/profile','LeadController@profile');
        Route::post('/leads/{lead}/update','LeadController@realtimeUpdate');
        Route::post('/leads/store/notes','LeadController@storenotes');
        Route::post('/leads/delete/notes','LeadController@deletenotes');
        Route::get('/leads/{note}/download','LeadController@download_notes_file');
        Route::post('/leads/notes/{note}/update','LeadController@update_note');
        Route::post('/leads/filter','LeadController@filter');
        Route::post('/leads/assign','LeadController@assign_leads');
        Route::get('leads/getdata','LeadController@getData');
        Route::post('/leads/getbranchdata','LeadController@getbranchdata');
        Route::get('leads/getfilterdata/{data}','LeadController@getFilterData');
        
    
    });
    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        Route::resource('/leads','LeadController');
    });
    /*------------------------------------------End of Leads-------------------------------------------------*/




    /*----------------------------------------------Entrust Routes------------------------------------------------------*/
    Route::group(['prefix'=>''],function(){
        Route::resource('/ipaddress','IpAddressCheckerController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/permission','PermissionController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/role','RoleController');
    });

    /*------------------------------------------End of Entrust Routes-------------------------------------------------*/

    
    /*----------------------------------------------User Routes-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/user','UserController');
    
    });

    /*------------------------------------------End of User Routes-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/company','CompanyController');
    });

    /*------------------------------------------End of Company-------------------------------------------------*/


    /*----------------------------------------------File -----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('files/proposals','FileController@proposals');
        Route::get('files/other-files','FileController@other_files');
        Route::post('files/download','FileController@download');
        Route::resource('/files','FileController');
    });

    /*------------------------------------------End of file-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/branch','BranchController');
        Route::post('/branch/getdata','BranchController@getdata');
    });

    /*--
    
    /*----------------------------------------------User Profile-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/profile','ProfileController');
    });

    /*------------------------------------------End of User Profile-------------------------------------------------*/

    /*----------------------------------------------Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/limit','LimitLeadsController');
    
    });


    /*----------------------------------------------End of Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('/migration/import','MigrationController@import');
        Route::post('/migration/upload','MigrationController@upload');
        Route::post('/migration/import/store','MigrationController@storefile');
        Route::get('/migration','MigrationController@import');  
    });

    /*------------------------------------------End of Leads-------------------------------------------------*/

    /*------------------------------------------Quota Routes-----------------------------------------------------------*/
        
        Route::resource('/quota','QuotaController');
    /*------------------------------------------End of Leads-------------------------------------------------*/

    }); //End of Middleware group

});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';

    protected $fillable = ['name'];

    public function branches(){
        return $this->hasMany('App\Branch','company_id','id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    public function __construct()
    {
        view()->share(['page_title' => 'Company']);
        $this->middleware('auth');
        $this->middleware(function ($request,$next){
           
            $this->company = Company::all();

            return $next($request);
         });      

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        view()->share(['breadcrumb' => 'Company','sub_breadcrumb'=> 'Lists']);
        return view('modules.company.index')
                ->with('company',$this->company);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = Company::create([
                    'name' => $request->company_name
                    ]);

        if($company){
            session()->flash('message','New company Successfully added!');           
        }else{
            session()->flash('error_message','Fail to add new company!');  
        }         

        return redirect('company');
                                
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        view()->share(['breadcrumb' => 'Company','sub_breadcrumb'=> 'Edit']);
        $company = Company::find($id);

        return view('modules.company.edit')
                ->with('company',$company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);

        $company->name = $request->company_name;

        if($company->save()){
            session()->flash('message','Company name successfully updated!');           
        }else{
            session()->flash('error_message','Fail to update company name!');  
        }         

        return redirect()->back();
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/modules/company/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
         <div class="row">
            <div class="col-lg-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Company Name</h5>
                        <div class="ibox-tools">
                            
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                         
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <form action="{{ url('company/'.$company->id) }}" method="POST" role="form">
                                <input type="hidden" name="_method" value="PUT">
                                    @csrf
                                <div class="form-group">
                                <input type="text" name="company_name" id="company_name" value="{{ $company->name }}" class="form-control" placeholder="Company Name" required/>
                                </div>
                                <div class="form-group">     
                                    <button class="ladda-button btn btn-block btn-primary" type="submit">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Company Branch</h5>
                        <div class="ibox-tools">
                            <button class="ladda-button btn btn-primary btn-xs" data-toggle="modal" data-target="#branchmodal"><i class="fa fa-plus"> New</i></button>   
                        </div>
                    </div>
                    <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-permission" >
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Branch Name</th>                                   
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($company->branches as $b)
                                    <tr>
                                        <td>
                                            {{ $b->id }}
                                        </td>
                                        <td>
                                        <a data-toggle="modal" data-target="#branch{{ $b->id }}">{{ $b->name }}</a>
                                        </td>
                                    </tr>
                                    <form action="{{ url('branch/'.$b->id) }}" method="POST" role="form">
                                        <input type="hidden" name="_method" value="PUT">
                                        @csrf
                                        <div class="modal inmodal" id="branch{{ $b->id }}" tabindex="-1" role="dialog" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content animated flipInY">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                                            <h4 class="modal-title">Add Branch</h4>                                    
                                                        </div>
                                                        <div class="modal-body">
                                                        <div class="form-group"><label>Branch Name</label> <input type="text" name="branch_name" value="{{ $b->name }}" placeholder="Enter branch name" class="form-control" required="required"></div>
                                                            
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-primary">Add </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    </form>   
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Branch Name</th>                         
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>
                {{-- start of modal --}}
                <form role="form" action="{{ route('branch.store') }}" method="POST">
                        @csrf
                    <div class="modal inmodal" id="branchmodal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content animated flipInY">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                    <h4 class="modal-title">Add Branch</h4>                                    
                                </div>
                                <div class="modal-body">
                                        <div class="form-group"><label>Branch Name</label> <input type="text" name="branch_name"  placeholder="Enter branch name" class="form-control" required="required"></div>
                                        <input type="hidden" name="company" value="{{ $company->id}}">
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Add </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                   {{-- end of modal --}}
            </div>
           
       </div>
    </div>
@endsection

@section('custom_js')
   <script>
       $(document).ready(function(){
           
       });
        //Keyboard shortcuts for creating notes
            Mousetrap.bind('N', function(){
                        $('#branchmodal').modal('toggle');
                  });
    
   </script>
@endsection

resources/views/modules/company/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
         <div class="row">
            
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Company Lists</h5>
                        <div class="ibox-tools">
                            <div class="ibox-tools">
                                <button class="ladda-button btn btn-primary btn-xs" data-toggle="modal" data-target="#companymodal"><i class="fa fa-plus"> New</i></button>   
                            </div>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-permission" >
                            <thead>
                                <tr>
                                    <th style="width:5%;"></th>
                                    <th>Name</th>
                                    <th>No. of Branch</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($company as $c)
                                    <tr>
                                        <td>{{ $c->id }}</td>
                                        <td><a href="{{ url('company/'.$c->id.'/edit') }}">{{ $c->name}} </a></td>
                                        <td></td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th style="width:5%;"></th>
                                    <th>Name</th>
                                    <th>No. of Branch</th>
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>

                {{-- start of modal --}}
                <form role="form" action="{{ route('company.store') }}" method="POST">
                        @csrf
                    <div class="modal inmodal" id="companymodal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content animated flipInY">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                    <h4 class="modal-title">Add Company</h4>                                    
                                </div>
                                <div class="modal-body">
                                        <div class="form-group"><label>Company Name</label> <input type="text" name="company_name"  placeholder="Enter company name" class="form-control" required="required"></div>
                                        
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Add </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                   {{-- end of modal --}}
            </div>
           
       </div>
    </div>
@endsection

@section('custom_js')
    <script>
        //Keyboard shortcuts for creating notes
        Mousetrap.bind('N', function(){
                        $('#companymodal').modal('toggle');
                  });
    </script>
@endsection