routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------------------------------ AUTH ROUTE SECTION -------------------------------------------------*/
    Route::get('/logout', 'Auth\LoginController@logout');
    
    Auth::routes();

Route::group(['middleware' => 'ip'], function() {

    Route::get('/', function () {
        
        return redirect('/home');
    });

    

    /*-------------------------------------------END OF ROUTE SECTION---------------------------------------------------*/
    Route::group(['middleware'=>'auth'],function(){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/load-more','HomeController@load_more');

    Route::get('/notifications', 'NotificationController@index');
    Route::delete('profile/{user}/notifications', function(App\User $user) {
        $user->notifications->map(function($n) {
            $n->markAsRead();
        });

        return back();
    });


    /*----------------------------------------------Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        
        Route::get('/leads/bucket-lists','LeadController@bucket_list');
        Route::get('/leads/bucket-lists-data','LeadController@bucket_list_data');
        Route::get('/leads/export','LeadController@export');
        Route::post('/leads/upload','LeadController@upload');
        Route::get('/leads/import','LeadController@import');
        Route::post('/leads/import/store','LeadController@storeimport');
        Route::get('/leads/{lead}/profile','LeadController@profile');
        Route::post('/leads/{lead}/update','LeadController@realtimeUpdate');
        Route::post('/leads/store/notes','LeadController@storenotes');
        Route::post('/leads/delete/notes','LeadController@deletenotes');
        Route::get('/leads/{note}/download','LeadController@download_notes_file');
        Route::post('/leads/notes/{note}/update','LeadController@update_note');
        Route::post('/leads/filter','LeadController@filter');
        Route::post('/leads/assign','LeadController@assign_leads');
        Route::get('leads/getdata','LeadController@getData');
        Route::post('/leads/getbranchdata','LeadController@getbranchdata');
        Route::get('leads/getfilterdata/{data}','LeadController@getFilterData');
        
    
    });
    Route::group(['prefix'=>'','middleware'=>['auth']],function(){
        Route::resource('/leads','LeadController');
    });
    /*------------------------------------------End of Leads-------------------------------------------------*/




    /*----------------------------------------------Entrust Routes------------------------------------------------------*/
    Route::group(['prefix'=>''],function(){
        Route::resource('/ipaddress','IpAddressCheckerController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/permission','PermissionController');
    });

    Route::group(['prefix'=>''],function(){
        Route::resource('/role','RoleController');
    });

    /*------------------------------------------End of Entrust Routes-------------------------------------------------*/

    
    /*----------------------------------------------User Routes-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/user','UserController');
    
    });

    /*------------------------------------------End of User Routes-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/company','CompanyController');
    });

    /*------------------------------------------End of Company-------------------------------------------------*/


    /*----------------------------------------------File -----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('files/proposals','FileController@proposals');
        Route::get('files/other-files','FileController@other_files');
        Route::post('files/download','FileController@download');
        Route::resource('/files','FileController');
    });

    /*------------------------------------------End of file-------------------------------------------------*/

    /*----------------------------------------------User Company-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/branch','BranchController');
        Route::post('/branch/getdata','BranchController@getdata');
    });

    /*--
    
    /*----------------------------------------------User Profile-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/profile','ProfileController');
    });

    /*------------------------------------------End of User Profile-------------------------------------------------*/

    /*----------------------------------------------Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::resource('/limit','LimitLeadsController');
    
    });


    /*----------------------------------------------End of Limit Leads-----------------------------------------------------------*/

    Route::group(['prefix'=>''],function(){
        Route::get('/migration/import','MigrationController@import');
        Route::post('/migration/upload','MigrationController@upload');
        Route::post('/migration/import/store','MigrationController@storefile');
        Route::get('/migration','MigrationController@import');  
    });

    /*------------------------------------------End of Leads-------------------------------------------------*/

    /*------------------------------------------Quota Routes-----------------------------------------------------------*/
        
        Route::resource('/quota','QuotaController');
    /*------------------------------------------End of Leads-------------------------------------------------*/

    }); //End of Middleware group

});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
    protected $fillable     = ['name','display_name','description','class'];

    public function getPermissions()
    {
        return $this->hasMany('App\PermissionRole','role_id','id');
    }

    public function getRoles()
    {
        return $this->hasMany('App\RoleUser','role_id','id');
    }

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Role;
use App\Permission;
use App\permissionRole;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function __construct()
    {
        view()->share(['page_title' => 'Role Setup',
                        'breadcrumb' => 'Role']);

         $this->roles = Role::All();   
         $this->permissions = Permission::All();            

         $this->middleware(function ($request,$next){

            return $next($request);
         });               
    }


    public function index()
    {
        view()->share(['sub_breadcrumb' => 'List']);

        return view('modules.role.index')
                ->with('roles',$this->roles);
    }

    public function create(){
        view()->share(['sub_breadcrumb' => 'Create']);
        return view('modules.role.create')
                ->with('permissions',$this->permissions);
    }

    public function store(Request $request)
    {
        
        DB::beginTransaction();
        
        $role = Role::create($request->all());

        $role->class = array_rand($this->get_class());
        

        if($role->save()){

            $role_id = $role->id;

            if($request->has('permissions')){
                 $this->add_permission_role($request->get('permissions'),$role_id);   
            }

            session()->flash('message','Role successfully saved!');

        }else{

            DB::rollBack();
            
            session()->flash('error_message','Fail to save role');  
        }
        
        DB::commit();

        return redirect()->back();

    }

    public function edit($role)
    {
        $roledata = Role::find($role);

        return view('modules.role.create')
                ->with('roledata',$roledata)
                ->with('permissions',$this->permissions);
    }

    public function update(Request $request,$role)
    {
            $role               = Role::find($role);
            $role->name         = $request->name;
            $role->display_name = $request->display_name;
            $role->description  = $request->description;
            
            if($role->save()){
                //remove all role permissions
                PermissionRole::Where('role_id',$role->id)->delete();

                if($request->has('permissions')){
                    //add permission role
                    $this->add_permission_role($request->permissions,$role->id);
                }
            }

            session()->flash('message','Role successfully updated!');
            return redirect('role');

            
    }

    public function add_permission_role($permissions,$role)
    {
        foreach($permissions as $permission)
        {
            PermissionRole::create(['permission_id'=>(int) $permission,'role_id'=>$role]);
        }
    }

    public function get_class()
    {

        $class = array(

             'label label-primary'  => 'label label-primary',
             'label label-info'     => 'label label-info',
             'label label-danger'   => 'label label-danger',
             'label label-warning'  => 'label label-warning',
             'label label-success'  => 'label label-success',
             'label label-default'  => 'label label-default'

        );

        return $class;
    }

}

resources/views/modules/role/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
         <div class="row">
         @if(isset($roledata))
             <form role="form" action="{{ url('role/'.$roledata->id) }}" method="POST">
             <input type="hidden" name="_method" value="PUT">
         @else
             <form role="form" action="{{ route('role.store') }}" method="POST">
         @endif
             @csrf
            <div class="col-lg-5">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Enter New Role </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                           
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12 ">                                   
                                    <div class="form-group"><label>Name</label> <input type="text" name="name" value="@if(isset($roledata)) {{ $roledata->name }} @endif" placeholder="Enter Name" class="form-control" required></div>
                                    <div class="form-group"><label>Display Name</label> <input type="text" name="display_name" value="@if(isset($roledata)) {{ $roledata->display_name }} @endif" placeholder="Enter Display Name" class="form-control" required> </div>
                                    <div class="form-group"><label>Description</label> <input type="text" name="description" value="@if(isset($roledata)) {{ $roledata->description }} @endif" placeholder="Enter Description" class="form-control" required></div>
                                    <div>
                                    <button class="ladda-button btn btn-primary pull-right" data-style="slide-right">Save</button>                               
                                    </div>                               
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Assign Permissions</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                                <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-roles" >
                            <thead>
                                <tr>
                                    <th style="width:5%;"><div class="i-checks"><label> <input type="checkbox" id="check-all" value=""></label></div></th>
                                    <th>Display Name</th>
                                    <th>Description</th>
                                
                                </tr>
                            </thead>
                            <tbody>
                             @foreach($permissions as $permission)
                                <tr>
                                    <td>
                                       @php
                                            $checked = '';
                                       @endphp 

                                       @if(count($permission->getRoles) > 0)
                                            @foreach($permission->getRoles as $roles)
                                                @if(isset($roledata))
                                                    @if($roles->role_id == $roledata->id)
                                                        @php
                                                             $checked = 'checked';
                                                        @endphp
                                                    @endif
                                                @endif
                                            @endforeach

                                        <div class="i-checks"><label> <input type="checkbox" name="permissions[]" value="{{ $permission->id }}" {{ $checked }}></label></div>
                                       @else
                                       <div class="i-checks"><label> <input type="checkbox" name="permissions[]" value="{{ $permission->id }}"></label></div>
                                       @endif 
                                    </td>
                                    <td style="color:#1ab394;">{{ $permission->display_name }}</td>
                                    <td>{{ $permission->description }}</td>
                                </tr>
                             @endforeach   
                             
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th style="width:5%;"><div class="i-checks"><label> <input type="checkbox" id="check-all" value=""></label></div></th>
                                    <th>Display Name</th>
                                    <th>Description</th>                                    
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>                
            </div>
            </form>
       </div>
    </div>
@endsection

@section('custom_js')
<script>
        $(document).ready(function(){
            $("#check-all").on("ifUnchecked",function(event){
                 //uncheck all checkboxes
                 $("input[type='checkbox']").iCheck("uncheck");
            });

            $("#check-all").on("ifChecked",function(event){
                 //uncheck all checkboxes
                 $("input[type='checkbox']").iCheck("check");
            });

        });
    </script>
@endsection

resources/views/modules/role/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
         <div class="row">
            
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Role Lists</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                                <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-permission" >
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Display Name</th>
                                    <th>Description</th>
                                
                                </tr>
                            </thead>
                            <tbody>
                             @foreach($roles as $role)
                                <tr>
                                    <td style="color:#1ab394;"><a href="{{ url('role/'.$role->id.'/edit/')}}">{{ $role->name }}</a></td>
                                    <td>{{ $role->display_name }}</td>
                                    <td>{{ $role->description }}</td>
                                </tr>
                             @endforeach   
                             
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Display Name</th>
                                    <th>Description</th>
                                    
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
           
       </div>
    </div>
@endsection

@section('custom_js')

@endsection